-- MySQL Script generated by MySQL Workbench
-- Thu Nov 25 16:08:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Db_Inscripcion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Db_Inscripcion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Db_Inscripcion` DEFAULT CHARACTER SET utf8 ;
USE `Db_Inscripcion` ;

-- -----------------------------------------------------
-- Table `Db_Inscripcion`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Inscripcion`.`Carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `NombreCarrera` VARCHAR(45) NULL,
  `FechaInscripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Inscripcion`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Inscripcion`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `NombreAlumno` VARCHAR(45) NULL,
  `ApellidoAlumno` VARCHAR(45) NULL,
  `MatriculaEstudiante` VARCHAR(45) NULL,
  `DireccionEstudiante` VARCHAR(45) NULL,
  `TelefonoEstudiante` VARCHAR(45) NULL,
  `CorreoEstudiante` VARCHAR(45) NULL,
  `idCarrera` INT NULL,
  `Carrera_idCarrera` INT NOT NULL,
  PRIMARY KEY (`idAlumno`, `Carrera_idCarrera`),
  INDEX `fk_Alumno_Carrera1_idx` (`Carrera_idCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera`)
    REFERENCES `Db_Inscripcion`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Inscripcion`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Inscripcion`.`Materia` (
  `idMateria` INT NOT NULL AUTO_INCREMENT,
  `MateriaNombre` VARCHAR(45) NULL,
  `MateriaHora` DATE NULL,
  `MateriaDia` DATE NULL,
  `MateriaAula` VARCHAR(45) NULL,
  `idAula` INT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Inscripcion`.`Maestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Inscripcion`.`Maestro` (
  `idMaestro` INT NOT NULL AUTO_INCREMENT,
  `MaestroNombre` VARCHAR(45) NULL,
  `MaestroApellido` VARCHAR(45) NULL,
  `MaestroTelefono` VARCHAR(45) NULL,
  `MaestroCorreo` VARCHAR(45) NULL,
  PRIMARY KEY (`idMaestro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Inscripcion`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Inscripcion`.`Aula` (
  `idAula` INT NOT NULL AUTO_INCREMENT,
  `AulaNumero` INT NULL,
  `AulaUbicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Inscripcion`.`Alumno_has_Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Inscripcion`.`Alumno_has_Materia` (
  `Alumno_idAlumno` INT NOT NULL,
  `Materia_idMateria` INT NOT NULL,
  PRIMARY KEY (`Alumno_idAlumno`, `Materia_idMateria`),
  INDEX `fk_Alumno_has_Materia_Materia1_idx` (`Materia_idMateria` ASC) VISIBLE,
  INDEX `fk_Alumno_has_Materia_Alumno_idx` (`Alumno_idAlumno` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_has_Materia_Alumno`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `Db_Inscripcion`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Materia_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `Db_Inscripcion`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Inscripcion`.`Materia_has_Maestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Inscripcion`.`Materia_has_Maestro` (
  `Materia_idMateria` INT NOT NULL,
  `Maestro_idMaestro` INT NOT NULL,
  PRIMARY KEY (`Materia_idMateria`, `Maestro_idMaestro`),
  INDEX `fk_Materia_has_Maestro_Maestro1_idx` (`Maestro_idMaestro` ASC) VISIBLE,
  INDEX `fk_Materia_has_Maestro_Materia1_idx` (`Materia_idMateria` ASC) VISIBLE,
  CONSTRAINT `fk_Materia_has_Maestro_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `Db_Inscripcion`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Maestro_Maestro1`
    FOREIGN KEY (`Maestro_idMaestro`)
    REFERENCES `Db_Inscripcion`.`Maestro` (`idMaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Db_Inscripcion`.`Materia_has_Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Db_Inscripcion`.`Materia_has_Aula` (
  `Materia_idMateria` INT NOT NULL,
  `Aula_idAula` INT NOT NULL,
  PRIMARY KEY (`Materia_idMateria`, `Aula_idAula`),
  INDEX `fk_Materia_has_Aula_Aula1_idx` (`Aula_idAula` ASC) VISIBLE,
  INDEX `fk_Materia_has_Aula_Materia1_idx` (`Materia_idMateria` ASC) VISIBLE,
  CONSTRAINT `fk_Materia_has_Aula_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `Db_Inscripcion`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Aula_Aula1`
    FOREIGN KEY (`Aula_idAula`)
    REFERENCES `Db_Inscripcion`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
